sudo: false
language: python
notifications:
  email: false
python:
  - 3.6
before_install:
  - pip install -r tests/requirements.txt
script:
  - nosetests --with-coverage --cover-package meetup_ballot tests && flake8 .
after_success:
  codecov
